FROM mysql:latest
 
MAINTAINER chonghuanwang <353022372@qq.com>

LABEL Descripttion="This image is build for MAC to use mysql" Vendor="GitHub" Version="latest"

RUN apt-get update && apt-get install -y vim curl wget lsof net-tools
